#!/bin/bash
source "/usr/share/LazySQL/.functions"
mv ~/zeus-scanner/zeus-scanner/log/url-log/* ~/zeus-scanner/zeus-scanner/log/url-log-old/
if [ -e ~/target ]
then
cat ~/target >> ~/target.old
rm ~/target
line="0"
else
line="0"
fi
#line=$(wc -l ~/target | cut -f1 -d" ")
while true; do
if [ $line -gt "25" ]
 then
  echo 'Crawling finished!'
  break
else
  ~/.mkbash/scripts/zeusr
  cat ~/zeus-scanner/zeus-scanner/log/url-log/* > ~/target
  line=$(wc -l ~/target | cut -f1 -d" ")
fi
done
multiauto
