#!/bin/bash
echo '#!/bin/bash
/usr/share/LazySQL/LazySQL "$@"' > /bin/lsql
chmod +x /bin/lsql
mkdir -p /usr/share/LazySQL/
cp -r * /usr/share/LazySQL/
cp .functions /usr/share/LazySQL/
tput smso;
echo "Installation/Update succesfull!"
tput rmso;
sleep 4

##install counter, no data exchanged. Use ## to disable.##
curl -s "https://counter7.wheredoyoucomefrom.ovh/private/freecounterstat.php?c=fp3gxwlcz273a7m4j8s55mklybumrt1t" > /dev/null

exit 0
