#!/bin/bash
echo '#!/bin/bash
/usr/share/LazySQL/LazySQL "$@"' > /bin/lsql
chmod +x /bin/lsql
mkdir -p /usr/share/LazySQL/
cp -r * /usr/share/LazySQL/
cp .functions /usr/share/LazySQL/
tput smso;
echo "Installation/Update succesfull!"
tput rmso;
sleep 4

##install counter, no data exchanged. Use ## to disable.##
curl -s "https://www.stat-counter.org/count/2iug" > /dev/null

exit 0
