#!/bin/bash
echo
echo "  ____                                ____   ___  _     ";
echo " |  _ \ ___  ___ _   _ _ __ ___   ___/ ___| / _ \| |    ";
echo " | |_) / _ \/ __| | | | '_ \` _ \ / _ \___ \| | | | |    ";
echo " |  _ <  __/\__ \ |_| | | | | | |  __/___) | |_| | |___ ";
echo " |_| \_\___||___/\__,_|_| |_| |_|\___|____/ \__\_\_____|";
echo "                                                        ";
echo
re='^[0-9]+$'
grep -q -c "" ~/.lsql.vul > ~/.lsqlc
count=$(cat ~/.lsqlc)
tput smso;
echo "Confirmed Url's:"
tput rmso;
cat -n ~/.lsql.vul

tput smso;
echo "Injection Number:"
tput rmso;

read -r line
echo
while true; do
	if ! [[ $line =~ $re ]] ; then
	 echo "Not a number!"
   tput smso;
	 echo "Injection Number:"
	 tput rmso;
	 read -r line
 else
	 break
	fi
done
#while true; do
#			 if [ $line -gt $count ]
#			   tput smso;
#    			   echo "This injection id doesnt exist!"
#			   tput rmso;
#			   echo
#			   echo "Please use a valid ID:"
#		   	   read -r line
#			  else
#			   break
#			 fi
#done

resumeurl=$(sed -n ""$line"p" ~/.lsql.vul | grep -o '^[^ ]\+')

tput smso;
echo "Resuming injection at:"
tput rmso;
echo $resumeurl | xclip -selection c
echo $resumeurl
sleep 5

exec lsql --fast
